services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:443"
    volumes:
      - /home/yulov/certs:/etc/ngnix/ssl
      # - ./certs:/etc/nginx/ssl
    depends_on:
      - backend
      